server:
  port: 9090
api:
  key: FXOVVXXHVCPVPBZXIJOBGUGSKHDNFRRQJP
auth:
  schema: S2S
id:
  chiave: 3202
accountId: 14537780
uri:
  baseUrl: https://sandbox.platfr.io
  cashAccount: /api/gbs/banking/v4.0/accounts/14537780
  cashAccountBalance: /api/gbs/banking/v4.0/accounts/{accountId}/balance
  cashAccountTransactions: /api/gbs/banking/v4.0/accounts/{accountId}/transactions